### ISSUE TITLE
Automatically pick up new notebooks in .gitlab-ci.yml

### ISSUE THREAD

**Issue by xbrianh** [DataBiosphere/bdcat_notebooks#41]
`.gitlab-ci.yml` should not need to be manually updated each time a new notebook is introduced.

Options:
  - define a job per notebook automatically, if possible
  - build all notebooks in a job

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TLP-1773)

**Comment by DailyDreaming** [comment]
@xbrianh A PR for option 2: https://github.com/DataBiosphere/bdcat_notebooks/pull/45
