### ISSUE TITLE
Include More Detailed Instructions

### ISSUE THREAD

**Issue by juklucas** [DataBiosphere/bdcat_notebooks#54]
It might be nice to include:

1. **Optional instructions to install pyenv**
```
brew install pyenv
pyenv install 3.7.3

echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.zshrc
```
Then switch to 3.7.3 with 
```
pyenv local 3.7.3
```
This would be nice for Mac users who are probably running python 3.8 and need to instal 3.7.

2. **An explicit instruction to update the publish.txt contents with the bucket for your destination workspace. (It is probably good to include an instruction on how to find that info as well.)**

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TLP-1770)

**Comment by xbrianh** [comment]
Does [this readme section](https://github.com/DataBiosphere/bdcat_notebooks#local-development-environment) address your comments?

**Comment by juklucas** [comment]
I was suggesting that you add to the current readme.md

* The first addition (how to install and use python 3.7) would go at the top of the *Local Development Environment* section.
* The second addition would go at the to of the *Publishing Notebooks* section
