### ISSUE TITLE
Inconsistency between make-test (errors out) and Terra (works perfectly)

### ISSUE THREAD

**Issue by aofarrel** [DataBiosphere/bdcat_notebooks#69]
It is possible for a notebook to pass mypy and lint, only to throw a TypeError, when `make test` is run, even though that same notebook can be fed through herzog, uploaded to Terra, and work perfectly fine. The error in question involves a dictionary being accessed by a string.

More info can be found [in this gist](https://gist.github.com/aofarrel/b21b1f0b42298a2d281357e24ae6f5d5). The notebook on the GWAS-1000G branch, in the first notebook's [main.py](https://github.com/DataBiosphere/bdcat_notebooks/blob/GWAS-1000G/notebooks/GWAS_1000_genomes_p1/main.py)

Miscellanous details:
- The notebook passing mypy and lint is not contingent on skipping the line in question (ie `# noqa` isn't just silencing an error)
- The notebook kernel being used on Terra is the default one, ie Python 3.7.7
- I didn't make any changes to this line when herzoging it; in other words, it has worked on Terra since at least late 2019 (it's based on 2019 ASHG)
- The notebook in question does run terra_data_table_util.ipynb prior to this line, but if I do not run that cell on a fresh environment, then the error still doesn't show, so I don't think terra_data_util is the reason behind the disrepency.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TLP-1769)

**Comment by xbrianh** [comment]
@aofarrel mypy and flake8 are [static analysis](https://en.wikipedia.org/wiki/Static_program_analysis) tools. They enforce style constraints and provide typing analysis, which is helpful for writing quality code.

If mypy is complaining, that's a hint that your program may do something that you don't expect, even if it seems to execute successfully.

**Comment by aofarrel** [comment]
That's not the issue I'm afraid. It passes mypy and lint without any issues or warnings, but fails upon execution. My understanding is, if a notebook passes those two, then fails, then it should fail on Terra. And yet, it doesn't, it works perfectly fine. In other words I think there is an inconsistency between the Python kernal on Terra and what's being run when a program is tested.

**Comment by aofarrel** [comment]
I've looked a little further into this and now I think the issue is that, when testing locally, fiss isn't actually pulling anything. So, instead of being a dictionary, it's treated as an empty list. Lists can't be indexed by strings hence the error.

**Comment by aofarrel** [comment]
fiss.fapi.list_entity_types(PROJECT, WORKSPACE).json() returns {‘causes’: [], ‘message’: ‘firecloud-cgl/cicd-tester-1000genomes-gwas does not exist’, ‘source’: ‘rawls’, ‘stackTrace’: [], ‘statusCode’: 404, ‘timestamp’: 1607733235055}183

But... why?

**Comment by aofarrel** [comment]
This was a permissions error; gitlab didn't have access to the workspace. Still having some pipeline issues but the root cause has changed, so I'm closing this.
