### ISSUE TITLE
bug in 1000G 2-gwas-initial-analysis notebook

### ISSUE THREAD

**Issue by bethsheets** [DataBiosphere/bdcat_notebooks#90]
The covariates list for sample set appears as "age,,sex,,population" which causes the GWAS workflow to fail. I think the fix may be to remove the space after the comma in the covariates.replace command:

if type(covariates) == list:
    sample_set['covariates'] = ", ".join(covariates)
elif covariates is not None:
    sample_set['covariates'] = covariates.replace(" ", ", ")
else:
    del sample_set['covariates']

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TLP-1800)

**Comment by aofarrel** [comment]
So far I haven't been able to replicate this, but I'll be giving it a go as I reorganize the 1000 Genomes branch.

**Comment by aofarrel** [comment]
This bug didn't appear to exist in the blood pressure TOPMed GWAS, even though the notebooks have a similar procedure. A quick comparison indicates why.

Blood pressure notebook's covariates:
`'age_at_bp_systolic,sex,antihypertensive_meds,bp_diastolic' `at [line 721](https://github.com/DataBiosphere/bdcat_notebooks/blob/5316bd1ab97e9016747866a0baeb2ad011f4e197/notebooks/GWAS_blood_pressure_p2/main.py#L721)

1000 Genomes notebook's covariates:
`covariates = "age, sex, population"` at [line 788](https://github.com/DataBiosphere/bdcat_notebooks/blob/bbc54853bc30be6fff14222daac52019e0b4e0ed/notebooks/GWAS_1000Genomes_p2/main.py#L788)

**Comment by aofarrel** [comment]
#94 solves this.
